import {AppStructure} from "@ctypes/appStructure";

const apps: AppStructure = {
    utorrent: {
        name: "µTorrent",
        command: "c:\\users\\ddl10\\appdata\\roaming\\utorrent\\utorrent.exe"
    },
    seven_zip_file_manager: {
        name: "7-Zip File Manager",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\7-zip\\7zfm.exe"
    },
    seven_zip_help: {
        name: "7-Zip Help",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\7-zip\\7-zip.chm"
    },
    about_java: {
        name: "About Java",
        command: "microsoft.autogenerated.{a5e73466-e220-8ef4-b956-a582187356d9}"
    },
    adobe_creative_cloud: {
        name: "Adobe Creative Cloud",
        command: "adobe.creativecloud"
    },
    aerosoft_one: {
        name: "Aerosoft One",
        command: "com.aerosoft.aerosoft-one"
    },
    ai_suite_3: {
        name: "AI Suite 3",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\asus\\ai suite iii\\aisuite3"
    },
    anydesk: {
        name: "AnyDesk",
        command: "prokzult ad"
    },
    apache_netbeans_ide_12_0: {
        name: "Apache NetBeans IDE 12.0",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\netbeans-12.0\\netbeans\\bin"
    },
    appflowy: {
        name: "AppFlowy",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\appflowy\\appflowy.exe"
    },
    application_verifier_wow: {
        name: "Application Verifier (WOW)",
        command: "{d65231b0-b2f1-4857-a4ce-a8e7c6ea7d27}\\appverif.exe"
    },
    application_verifier_x64: {
        name: "Application Verifier (X64)",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\appverif.exe"
    },
    armoury_crate: {
        name: "ARMOURY CRATE",
        command: "b9eced6f.armourycrate_qmba6cd70vzyy!app"
    },
    aukzip: {
        name: "AukZip",
        command: "57868codaapp.37800eedb46f1_4bn2s5v6tep1y!app"
    },
    aura_creator: {
        name: "Aura Creator",
        command: "b9eced6f.auracreator_qmba6cd70vzyy!app"
    },
    battle_net: {
        name: "Battle.net",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\battle.net\\battle.net launcher.exe"
    },
    bitnami_for_xampp: {
        name: "Bitnami for XAMPP",
        command: "https://bitnami.com/stack/xampp?utm_source=bitnami&utm_medium=installer"
    },
    brawlhalla: {
        name: "Brawlhalla",
        command: "steam://rungameid/291550"
    },
    character_map: {
        name: "Character Map",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\charmap.exe"
    },
    check_for_updates: {
        name: "Check For Updates",
        command: "microsoft.autogenerated.{2f519bf2-c697-59f8-8f6a-1e19509ce66b}"
    },
    chivalry_2: {
        name: "Chivalry 2",
        command: "tripwireinteractive.llc.chivalry2_237dqjpew1r3m!appchivalry2shipping"
    },
    clownfish_voice_changer: {
        name: "Clownfish Voice Changer",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\clownfishvoicechanger\\clownfishvoicechanger.exe"
    },
    command_prompt: {
        name: "Command Prompt",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\cmd.exe"
    },
    component_services: {
        name: "Component Services",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\comexp.msc"
    },
    computer_management: {
        name: "Computer Management",
        command: "microsoft.autogenerated.{8abd94fb-e7d6-84a6-a997-c918edde0ae5}"
    },
    configure_hex_editor_neo: {
        name: "Configure Hex Editor Neo",
        command: "microsoft.autogenerated.{15133395-d302-d281-d5cc-e3eb88c82a9e}"
    },
    configure_java: {
        name: "Configure Java",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\java\\jre-1.8\\bin\\javacpl.exe"
    },
    control_panel: {
        name: "Control Panel",
        command: "microsoft.autogenerated.{854b37fe-df8e-a80c-4114-adfdd0d9f1cb}"
    },
    copilot: {
        name: "Copilot",
        command: "microsoft.copilot_8wekyb3d8bbwe!app"
    },
    cortana: {
        name: "Cortana",
        command: "microsoft.549981c3f5f10_8wekyb3d8bbwe!app"
    },
    court_digital_signature_application: {
        name: "Court Digital Signature Application",
        command: "c:\\ngcs\\court digital signature application\\signtest.exe"
    },
    credits: {
        name: "Credits",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\mremoteng\\credits.txt"
    },
    curseforge: {
        name: "CurseForge",
        command: "com.overwolf.curseforge"
    },
    debug_package_manager_2: {
        name: "Debuggable Package Manager (2)",
        command: "microsoft.autogenerated.{96690f80-0b7f-841e-e0db-cc38ac5c839f}"
    },
    defragment_and_optimize_drives: {
        name: "Defragment and Optimize Drives",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\dfrgui.exe"
    },
    dev_home: {
        name: "Dev Home",
        command: "microsoft.windows.devhome_8wekyb3d8bbwe!app"
    },
    developer_command_prompt_vs_2019: {
        name: "Developer Command Prompt for VS 2019",
        command: "microsoft.autogenerated.{4bea08d7-78e4-19ac-6b39-fa0525ba34fb}"
    },
    developer_command_prompt_vs_2019_2: {
        name: "Developer Command Prompt for VS 2019 (2)",
        command: "microsoft.autogenerated.{c3599397-6a99-f41c-503e-788f649830af}"
    },
    developer_powershell_vs_2019: {
        name: "Developer PowerShell for VS 2019",
        command: "microsoft.autogenerated.{27745da3-7d10-0907-37e9-cfcdf6e3c292}"
    },
    developer_powershell_vs_2019_2: {
        name: "Developer PowerShell for VS 2019 (2)",
        command: "microsoft.autogenerated.{e509a72e-7e64-1124-2e9e-7c567b6f22bd}"
    },
    discord: {
        name: "Discord",
        command: "com.squirrel.discord.discord"
    },
    disk_cleanup: {
        name: "Disk Cleanup",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\cleanmgr.exe"
    },
    disney_plus: {
        name: "Disney+",
        command: "disney.37853fc22b2ce_6rarf9sa4v8jt!app"
    },
    docker_desktop: {
        name: "Docker Desktop",
        command: "docker.dockerforwindows.settings"
    },
    documentation: {
        name: "Documentation",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\mysql\\mysql for visual studio\\documentation"
    },
    documentation_for_desktop_apps: {
        name: "Documentation for Desktop Apps",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\windows kits\\10\\shortcuts\\documentation for desktop apps"
    },
    documentation_for_windows_store_apps: {
        name: "Documentation for Windows Store Apps",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\windows kits\\10\\shortcuts\\documentation for windows store apps"
    },
    driver_easy: {
        name: "Driver Easy",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\easeware\\drivereasy\\drivereasy.exe"
    },
    drug_dealer_simulator_2: {
        name: "Drug Dealer Simulator 2",
        command: "steam://rungameid/1708850"
    },
    epic_games_launcher: {
        name: "Epic Games Launcher",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\epic games\\launcher\\portal.bat"
    },
    event_viewer: {
        name: "Event Viewer",
        command: "microsoft.autogenerated.{bb044bfd-25b7-2faa-22a8-6371a93e0456}"
    },
    facebook: {
        name: "Facebook",
        command: "facebook.facebook_8xx8rvfyw5nnt!app"
    },
    file_explorer: {
        name: "File Explorer",
        command: "microsoft.windows.explorer"
    },
    filezilla: {
        name: "FileZilla",
        command: "filezilla.client.appid"
    },
    firmware_update: {
        name: "Firmware Update",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\guillemot\\tmfwupdater\\tmfirmwareupdater.exe"
    },
    firmware_update_tool: {
        name: "FirmwareUpdateTool",
        command: "c:\\programdata\\logishrd\\logioptions\\deviceupdater\\firmwareupdatetool.exe"
    },
    fivem: {
        name: "FiveM",
        command: "citizenfx.fivem.client"
    },
    game_bar: {
        name: "Game Bar",
        command: "microsoft.xboxgamingoverlay_8wekyb3d8bbwe!app"
    },
    gaming_intelligence: {
        name: "GamingIntelligence",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\gamingintelligence\\gamingintelligence.exe"
    },
    general_help: {
        name: "General help",
        command: "https://www.heidisql.com/help.php?place=startmenu"
    },
    get_help: {
        name: "Get Help",
        command: "https://java.com/help"
    },
    get_started: {
        name: "Get Started",
        command: "microsoftwindows.client.cbs_cw5n1h2txyewy!webexperiencehost"
    },
    git_bash: {
        name: "Git Bash",
        command: "microsoft.autogenerated.{0fdd9c6b-656b-0f1f-ab08-b1cdbb7067b3}"
    },
    git_cmd: {
        name: "Git CMD",
        command: "microsoft.autogenerated.{29591c0f-7c09-b655-c0eb-8544fca7d1de}"
    },
    git_faqs: {
        name: "Git FAQs (Frequently Asked Questions)",
        command: "https://github.com/git-for-windows/git/wiki/faq"
    },
    git_gui: {
        name: "Git GUI",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\git\\cmd\\git-gui.exe"
    },
    git_release_notes: {
        name: "Git Release Notes",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\git\\releasenotes.html"
    },
    github: {
        name: "GitHub",
        command: "chrome._crx_mjoklplbddpnokjaffbmgbkkgg"
    },
    google_chrome: {
        name: "Google Chrome",
        command: "chrome"
    },
    google_drive: {
        name: "Google Drive",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\google\\drive file stream\\92.0.0.0\\googledrivefs.exe"
    },
    grand_theft_auto_v: {
        name: "Grand Theft Auto V",
        command: "steam://rungameid/271590"
    },
    heidisql: {
        name: "HeidiSQL",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\heidisql\\heidisql.exe"
    },
    help_eng: {
        name: "Help (ENG)",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\windirstat\\windirstat.chm"
    },
    hex_editor_neo: {
        name: "Hex Editor Neo",
        command: "c:\\users\\ddl10\\appdata\\local\\hhd software\\hex editor neo\\hexframework.exe"
    },
    hex_editor_neo_documentation: {
        name: "Hex Editor Neo Documentation",
        command: "c:\\users\\ddl10\\appdata\\local\\hhd software\\hex editor neo\\hex editor neo documentation.chm"
    },
    hex_editor_neo_patch_api_documentation: {
        name: "Hex Editor Neo Patch API Documentation",
        command: "c:\\users\\ddl10\\appdata\\local\\hhd software\\hex editor neo\\patchapi\\hexpatchapi.doc"
    },
    hidhide_configuration_client: {
        name: "HidHide Configuration Client",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\nefarius software solutions\\hidhide\\configurationclient.exe"
    },
    hyper_v_manager: {
        name: "Hyper-V Manager",
        command: "microsoft.autogenerated.{7dfc4b93-681d-7b96-03e1-ae81fb7e597a}"
    },
    hyper_v_quick_create: {
        name: "Hyper-V Quick Create",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\hyper-v\\vmcreate.exe"
    },
    idle_python_3_12_64_bit: {
        name: "IDLE (Python 3.12 64-bit)",
        command: "microsoft.autogenerated.{da53df9e-b9d5-620d-c1c9-8e3212d987b1}"
    },
    idle_python_3_9_64_bit: {
        name: "IDLE (Python 3.9 64-bit)",
        command: "microsoft.autogenerated.{2ef45c87-d17c-6a51-914b-a77653247768}"
    },
    idle_python_3_9: {
        name: "IDLE (Python 3.9)",
        command: "pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0!idle"
    },
    instagram_1: {
        name: "Instagram",
        command: "facebook.instagrambeta_8xx8rvfyw5nnt!app"
    },
    instagram_2: {
        name: "Instagram",
        command: "www.instagram.com-3d2aae46_ysfa6mcnwr1rw!app"
    },
    install_additional_tools_node_js: {
        name: "Install Additional Tools for Node.js",
        command: "microsoft.autogenerated.{04770c2d-34e6-be94-efad-fa817237d6e9}"
    },
    iscsi_initiator: {
        name: "iSCSI Initiator",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\iscsicpl.exe"
    },
    lens: {
        name: "Lens",
        command: "com.electron.kontena-lens"
    },
    license: {
        name: "License",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\mremoteng\\license.txt"
    },
    limitless: {
        name: "Limitless",
        command: "microsoft.limitless_8wekyb3d8bbwe!game"
    },
    linkedin: {
        name: "LinkedIn",
        command: "7ee7776c.linkedinforwindows_w1wdnht996qgy!app"
    },
    live_captions: {
        name: "Live captions",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\livecaptions.exe"
    },
    local: {
        name: "Local",
        command: "com.getflywheel.lightning.local"
    },
    local_security_policy: {
        name: "Local Security Policy",
        command: "microsoft.autogenerated.{bd3f924e-55fb-a1ba-9de6-b50f9f2460ac}"
    },
    logi_bolt: {
        name: "Logi Bolt",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\logi\\logibolt\\logibolt.exe"
    },
    logi_options_plus: {
        name: "Logi Options+",
        command: "logi.optionsplus.app"
    },
    logi_plugin_service: {
        name: "Logi Plugin Service",
        command: "microsoft.autogenerated.{4b1dca4c-ecfe-0376-3389-4e1859f1b895}"
    },
    logitech_options: {
        name: "Logitech Options",
        command: "logitech.logioptions"
    },
    magnifier: {
        name: "Magnifier",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\magnify.exe"
    },
    maps: {
        name: "Maps",
        command: "microsoft.windowsmaps_8wekyb3d8bbwe!app"
    },
    medal: {
        name: "Medal",
        command: "com.squirrel.medal.medal"
    },
    microsoft_365_office: {
        name: "Microsoft 365 (Office)",
        command: "microsoft.microsoftofficehub_8wekyb3d8bbwe!microsoft.microsoftofficehub"
    },
    microsoft_clipchamp: {
        name: "Microsoft Clipchamp",
        command: "clipchamp.clipchamp_yxz26nhyzhsrt!app"
    },
    microsoft_edge: {
        name: "Microsoft Edge",
        command: "msedge"
    },
    microsoft_flight_simulator: {
        name: "Microsoft Flight Simulator",
        command: "microsoft.flightsimulator_8wekyb3d8bbwe!app"
    },
    microsoft_news: {
        name: "Microsoft News",
        command: "microsoft.bingnews_8wekyb3d8bbwe!appexnews"
    },
    microsoft_store: {
        name: "Microsoft Store",
        command: "microsoft.windowsstore_8wekyb3d8bbwe!app"
    },
    microsoft_to_do: {
        name: "Microsoft To Do",
        command: "microsoft.todos_8wekyb3d8bbwe!app"
    },
    minikube: {
        name: "Minikube",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\kubernetes\\minikube\\minikube.exe"
    },
    mixed_reality_portal: {
        name: "Mixed Reality Portal",
        command: "microsoft.mixedreality.portal_8wekyb3d8bbwe!app"
    },
    mobadiff: {
        name: "MobaDiff",
        command: "microsoft.autogenerated.{4dd6cd53-1f85-d73a-bf5e-533d476f8df9}"
    },
    mobatexteditor: {
        name: "MobaTextEditor",
        command: "microsoft.autogenerated.{af3c331f-138a-da8b-d6f9-f1a9635a8983}"
    },
    mobaxterm: {
        name: "MobaXterm",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\mobatek\\mobaxterm\\mobaxterm.exe"
    },
    mongodb_compass: {
        name: "MongoDBCompass",
        command: "com.squirrel.mongodbcompass.mongodbcompass"
    },
    mremoteng: {
        name: "mRemoteNG",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\mremoteng\\mremoteng.exe"
    },
    mysql_installer_community: {
        name: "MySQL Installer - Community",
        command: "microsoft.autogenerated.{2c7c9013-a7fd-5c12-d811-939afe2a3592}"
    },
    mysql_workbench_8_0_ce: {
        name: "MySQL Workbench 8.0 CE",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\mysql\\mysql workbench 8.0 ce\\mysqlworkbench.exe"
    },
    narrator: {
        name: "Narrator",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\narrator.exe"
    },
    node_js: {
        name: "Node.js",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\nodejs\\node.exe"
    },
    node_js_command_prompt: {
        name: "Node.js command prompt",
        command: "microsoft.autogenerated.{499ee7ca-7ed5-ebc9-ab09-80dc143d7b90}"
    },
    node_js_documentation: {
        name: "Node.js documentation",
        command: "https://nodejs.org/download/release/v20.11.1/docs/api/"
    },
    node_js_website: {
        name: "Node.js website",
        command: "https://nodejs.org/"
    },
    nordvpn: {
        name: "NordVPN",
        command: "nordvpn"
    },
    nordvpn_diagnostics: {
        name: "NordVPN Diagnostics",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\nordvpn\\6.45.5.0\\diagnostics.exe"
    },
    notification_manager_adobe_creative_cloud: {
        name: "Notification Manager for Adobe Creative Cloud",
        command: "adobenotificationclient_enpm4xejd91yc!creativecloud"
    },
    nvidia: {
        name: "NVIDIA",
        command: "com.nvidia.nvapp"
    },
    nvidia_control_panel: {
        name: "NVIDIA Control Panel",
        command: "nvidiacorp.nvidiacontrolpanel_56jybvy8sckqj!nvidiacorp.nvidiacontrolpanel"
    },
    obs_studio_64bit: {
        name: "OBS Studio (64bit)",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\obs-studio\\bin\\64bit\\obs64.exe"
    },
    odbc_data_sources_32_bit: {
        name: "ODBC Data Sources (32-bit)",
        command: "{d65231b0-b2f1-4857-a4ce-a8e7c6ea7d27}\\odbcad32.exe"
    },
    odbc_data_sources_64_bit: {
        name: "ODBC Data Sources (64-bit)",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\odbcad32.exe"
    },
    onedrive: {
        name: "OneDrive",
        command: "microsoft.skydrive.desktop"
    },
    onenote_windows_10: {
        name: "OneNote for Windows 10",
        command: "microsoft.office.onenote_8wekyb3d8bbwe!microsoft.onenoteim"
    },
    on_screen_keyboard: {
        name: "On-Screen Keyboard",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\osk.exe"
    },
    openiv: {
        name: "OpenIV",
        command: "c:\\users\\ddl10\\appdata\\local\\new technology studio\\apps\\openiv\\openiv.exe"
    },
    outlook_new: {
        name: "Outlook (new)",
        command: "microsoft.outlookforwindows_8wekyb3d8bbwe!microsoft.outlookforwindows"
    },
    pageant: {
        name: "Pageant",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\putty\\pageant.exe"
    },
    pc_health_check: {
        name: "PC Health Check",
        command: "c:\\users\\ddl10\\appdata\\local\\pchealthcheck\\pchealthcheck.exe"
    },
    performance_monitor: {
        name: "Performance Monitor",
        command: "microsoft.autogenerated.{8aa47365-b2b3-1961-69eb-f866e376b12f}"
    },
    phpstorm_2024_1: {
        name: "PhpStorm 2024.1",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\jetbrains\\phpstorm 2024.1\\bin\\phpstorm64.exe"
    },
    postman: {
        name: "Postman",
        command: "com.squirrel.postman.postman"
    },
    postman_website: {
        name: "Postman Website",
        command: "chrome._crx_ocfehogooeobepmlnmphlljbbo"
    },
    power_automate: {
        name: "Power Automate",
        command: "microsoft.powerautomatedesktop_8wekyb3d8bbwe!pad.console"
    },
    print_management: {
        name: "Print Management",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\printmanagement.msc"
    },
    psftp: {
        name: "PSFTP",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\putty\\psftp.exe"
    },
    putty: {
        name: "PuTTY",
        command: "simontatham.putty"
    },
    putty_manual: {
        name: "PuTTY Manual",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\putty\\putty.chm"
    },
    putty_web_site: {
        name: "PuTTY Web Site",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\putty\\website.url"
    },
    puttygen: {
        name: "PuTTYgen",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\putty\\puttygen.exe"
    },
    python_3_12_64_bit: {
        name: "Python 3.12 (64-bit)",
        command: "c:\\python312\\python.exe"
    },
    python_3_12_manuals_64_bit: {
        name: "Python 3.12 Manuals (64-bit)",
        command: "c:\\python312\\doc\\html\\index.html"
    },
    python_3_12_module_docs_64_bit: {
        name: "Python 3.12 Module Docs (64-bit)",
        command: "microsoft.autogenerated.{e21962e1-e576-b839-6a05-47ef771fbd9c}"
    },
    python_3_9: {
        name: "Python 3.9",
        command: "pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0!python"
    },
    python_3_9_64_bit: {
        name: "Python 3.9 (64-bit)",
        command: "c:\\users\\ddl10\\appdata\\local\\programs\\python\\python39\\python.exe"
    },
    python_3_9_module_docs_64_bit: {
        name: "Python 3.9 Module Docs (64-bit)",
        command: "microsoft.autogenerated.{0feb7440-f069-2d3b-0e0a-59c5f0c32cb0}"
    },
    readme: {
        name: "Readme",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\mremoteng\\readme.txt"
    },
    recovery_drive: {
        name: "Recovery Drive",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\recoverydrive.exe"
    },
    redis_insight: {
        name: "Redis Insight",
        command: "org.redislabs.redisinsight-v2"
    },
    reference_documentation: {
        name: "Reference Documentation",
        command: "https://docs.oracle.com/javase/8/docs"
    },
    registry_editor: {
        name: "Registry Editor",
        command: "{f38bf404-1d43-42f2-9305-67de0b28fc23}\\regedit.exe"
    },
    release_notes_1: {
        name: "Release Notes",
        command: "http://www.hhdsoftware.com/dispatch/hex/release-notes?type=startmenu"
    },
    release_notes_2: {
        name: "Release Notes",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\mysql\\mysql for visual studio\\releasenotes.html"
    },
    remote_desktop: {
        name: "Remote Desktop",
        command: "microsoft.remotedesktop_8wekyb3d8bbwe!app"
    },
    remote_desktop_connection: {
        name: "Remote Desktop Connection",
        command: "microsoft.windows.remotedesktop"
    },
    remote_viewer: {
        name: "Remote viewer",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\virtviewer v11.0-256\\bin\\remote-viewer.exe"
    },
    resource_monitor: {
        name: "Resource Monitor",
        command: "microsoft.autogenerated.{c804bba7-fa5f-cbf7-8b55-2096e5f972cb}"
    },
    rockstar_games_launcher: {
        name: "Rockstar Games Launcher",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\rockstar games\\launcher\\launcher.exe"
    },
    run: {
        name: "Run",
        command: "microsoft.windows.shell.rundialog"
    },
    ryzen_master: {
        name: "Ryzen Master",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\amd\\ryzenmaster\\bin\\amd ryzen master.exe"
    },
    ryzen_master_help_guide: {
        name: "Ryzen Master Help Guide",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\amd\\ryzenmaster\\documentation\\amd ryzen master help.pdf"
    },
    samples_for_desktop_apps: {
        name: "Samples for Desktop Apps",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\windows kits\\10\\shortcuts\\samples for desktop apps"
    },
    samples_for_windows_store_apps: {
        name: "Samples for Windows Store Apps",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\windows kits\\10\\shortcuts\\samples for windows store apps"
    },
    services: {
        name: "Services",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\services.msc"
    },
    settings: {
        name: "Settings",
        command: "windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel"
    },
    skype: {
        name: "Skype",
        command: "microsoft.skypeapp_kzf8qxf38zg5c!app"
    },
    solitaire_casual_games: {
        name: "Solitaire & Casual Games",
        command: "microsoft.microsoftsolitairecollection_8wekyb3d8bbwe!app"
    },
    sox: {
        name: "sox.exe",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\sox-14-4-2\\sox.exe"
    },
    speak_to_my_computer: {
        name: "Speak To My Computer",
        command: "com.example.myapp"
    },
    spotify: {
        name: "Spotify",
        command: "spotifyab.spotifymusic_zpdnekdrzrea0!spotify"
    },
    steam: {
        name: "Steam",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\steam\\steam.exe"
    },
    steam_support_center: {
        name: "Steam Support Center",
        command: "http://support.steampowered.com/"
    },
    steps_recorder: {
        name: "Steps Recorder",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\psr.exe"
    },
    studio_3t: {
        name: "Studio 3T",
        command: "{6d809377-6af0-444b-8957-a3773f02200e}\\3t software labs\\studio 3t\\studio-3t.exe"
    },
    system_configuration: {
        name: "System Configuration",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\msconfig.exe"
    },
    system_information: {
        name: "System Information",
        command: "{1ac14e77-02e7-4e5d-b744-2eb1ae5198b7}\\msinfo32.exe"
    },
    target_gui: {
        name: "TARGET GUI",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\thrustmaster\\target\\x64\\target_gui.exe"
    },
    target_script_editor: {
        name: "TARGET Script Editor",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\thrustmaster\\target\\x64\\target_script_editor.exe"
    },
    task_manager: {
        name: "Task Manager",
        command: "microsoft.autogenerated.{923dd477-5846-686b-a659-0fccd73851a8}"
    },
    task_scheduler: {
        name: "Task Scheduler",
        command: "microsoft.autogenerated.{c1c6f8ac-40a3-0f5c-146f-65a9dc70bbb4}"
    },
    tools_for_desktop_apps: {
        name: "Tools for Desktop Apps",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\windows kits\\10\\shortcuts\\tools for desktop apps"
    },
    tools_for_windows_store_apps: {
        name: "Tools for Windows Store Apps",
        command: "{7c5a40ef-a0fb-4bfc-874a-c0f2e0b9fa8e}\\windows kits\\10\\shortcuts\\tools for windows store apps"
    },
    twilio_console: {
        name: "Twilio Console",
        command: "chrome._crx_lgpibobjhbjnion.userdata.profile5"
    },
    ubisoft_connect: {
        name: "Ubisoft Connect",
        command: "ubisoft.upc.mainprocess"
    },
    ubuntu_24_04_1_lts: {
        name: "Ubuntu 24.04.1 LTS",
        command: "canonicalgrouplimited.ubuntu24.04lts_79rhkp1fndgsc!ubuntu240"
    }
}

export default apps